{
	parserClass='org.lice.lang.LiceParser'
	extends='com.intellij.extapi.psi.ASTWrapperPsiElement'
	psiClassPrefix='Lice'
	psiImplClassSuffix='Impl'
	psiPackage='org.lice.lang.psi'
	psiImplPackage='org.lice.lang.psi.impl'

	tokenTypeClass='org.lice.lang.LiceTokenType'
	elementTypeHolderClass='org.lice.lang.psi.LiceTypes'
	elementTypeClass='org.lice.lang.LiceElementType'
	psiImplUtilClass='org.lice.lang.psi.impl.LicePsiImplUtils'
}

file ::= element*
element ::= STR | numberOrSymbol | COMMENT | null | methodCall
null ::= LEFT_BRACKET RIGHT_BRACKET

methodCall ::= LEFT_BRACKET element+ RIGHT_BRACKET {
	methods=[getCallee]
}

numberOrSymbol ::= SYM | NUMBER
