{

	parserClass="org.lice.lang.LiceParser"
	parserUtilClass="com.intellij.lang.parser.GeneratedParserUtilBase"
	extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

	psiClassPrefix="Lice"
	psiImplClassSuffix="Impl"
	psiPackage="org.lice.lang.psi"
	psiImplPackage="org.lice.lang.psi.impl"

	elementTypeHolderClass="org.lice.lang.psi.LiceTypes"
	elementTypeClass="org.lice.lang.psi.LiceElementType"
	tokenTypeClass="org.lice.lang.psi.LiceTokenType"

//	psiImplUtilClass="org.lice.lang.psi.impl.LicePsiImplUtil"

	tokens = [
		BOOL                 = "regexp:true|false"
		SEPERATOR            = "regexp:[\s|,，　]+"
		NULL                 = "null"
		LPAREN               = "regexp:[(（]"
		RPAREN               = "regexp:[）)]"
		COMMENT              = "regexp:[;；][^\n]*[\n]?"
		INTEGER              = "regexp:([1-9][\d]*[Nn]?)|(0[0-7]*)|(0[xX](\d|[a-f]|[A-F])+)|(0[bB][01]+)"
		///                             10进制      高精度    8进制     16进制                      2进制
		FLOAT                = "regexp:(-?\d+)(\.\d+)?[fF]?"
		SYMBOL               = "regexp:[^\n\r；; 　,()（）]+"
		LITERAL              = "regexp:\"[^\"]*\""
	]
}

LICE_FILE ::= (EXPRESSION|COMMENT)*

EXPRESSION ::= SYMBOL
        | INTEGER
        | FLOAT
        | BOOL
        | LITERAL
        | NULL
        | LPAREN SYMBOL {EXPRESSION}* RPAREN

