{

	parserClass="org.lice.lang.LiceParser"
  parserUtilClass="org.lice.lang.LiceParserUtil"
	extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

	psiClassPrefix="Lice"
	psiImplClassSuffix="Impl"
	psiPackage="org.lice.lang.psi"
	psiPackage="org.lice.lang.psi.impl"

	elementTypeHolderClass="org.lice.lang.psi.LiceTypes"
	elementTypeClass="org.lice.lang.psi.LiceElementType"
	tokenTypeClass="org.lice.lang.psi.LiceTokenType"

//	psiImplUtilClass="org.lice.lang.psi.impl.LicePsiImplUtil"

	tokens = [
		bool = "regexp:true|false"
		null = 'null'
	]

}

liceFile ::= (stmt|comment)*

stmt ::= '(' stmt_body ')' | symbol | number | bool | literal
stmt_body ::= (symbol | stmt)*

comment ::= ";" {}
